document.getElementById('year').textContent=new Date().getFullYear();const phrases=["Frontend Engineer · React","APIs & Flask · Node.js","Data-driven · Python · SQL","Clean UX · Accessible UI"];const tw=document.getElementById('typewriter');const caret=document.querySelector('.caret');let pIndex=0,cIndex=0,deleting=!1,pause=1200;function typeLoop(){const current=phrases[pIndex];if(!deleting){tw.textContent=current.slice(0,++cIndex);if(cIndex===current.length){deleting=!0;setTimeout(typeLoop,pause);return}}else{tw.textContent=current.slice(0,--cIndex);if(cIndex===0){deleting=!1;pIndex=(pIndex+1)%phrases.length}}
const speed=deleting?28:48;setTimeout(typeLoop,speed+Math.random()*40)}
typeLoop();document.querySelectorAll('.ps-h, .ps-nav a').forEach(el=>{const alt=el.getAttribute('data-alt');if(!alt)return;let swapping=!1;const baseText=el.textContent;const swapOnce=()=>{if(swapping)return;swapping=!0;const original=el.textContent;el.textContent=alt;el.style.filter='contrast(120%)';el.animate([{transform:'translate(0,0)'},{transform:'translate(-1px,0)'},{transform:'translate(1px,0)'},{transform:'translate(0,0)'}],{duration:220,iterations:1});setTimeout(()=>{el.textContent=original;el.style.filter='';swapping=!1},480)};el.addEventListener('mouseenter',swapOnce)});const words=["+","HANDLE_WITH_CARE;","⌀","♡♡","<_steady_aim;","XX","XY","××","×","OOOO","OOO","XX_XX","▣▣▣","····","⇱⇲","⌗","⌗⌗","▤▤","==","MANTRA;","_precise_flick;","CTRL//CMD","[SAFE]","◯ ◯","□□□□","////","XXXX","B42;","▦▦▦","▣ XX","◯","⧉⧉⧉","██","██████","|||","XXO","++","###"];const bg=document.getElementById('ps-bg');const isMobile=matchMedia('(max-width: 980px)').matches;const MAX=isMobile?16:26;const placedPositions=[];const MIN_DISTANCE=50;function isTooClose(x,y){return placedPositions.some(pos=>{const dx=pos.x-x;const dy=pos.y-y;return Math.sqrt(dx*dx+dy*dy)<MIN_DISTANCE})}
function spawnGlitch(){if(!bg)return;const s=document.createElement('span');s.className='ps-glitch';s.textContent=words[Math.floor(Math.random()*words.length)];const vw=window.innerWidth;const vh=window.innerHeight;let x,y,tries=0;do{x=Math.random()*vw;y=Math.random()*vh;tries++}while(isTooClose(x,y)&&tries<10);placedPositions.push({x,y});s.style.left=x+'px';s.style.top=y+'px';s.style.fontSize=(Math.random()*12+12)+'px';s.style.setProperty('--angle',(Math.random()*6-3).toFixed(2));bg.appendChild(s);setTimeout(()=>{s.remove();const idx=placedPositions.findIndex(pos=>pos.x===x&&pos.y===y);if(idx>-1)placedPositions.splice(idx,1);},3000)}
let active=0;function bgLoop(){if(active<MAX){spawnGlitch();active++;setTimeout(()=>{active--},1200)}
setTimeout(bgLoop,isMobile?220:140)}
bgLoop();if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.caret').forEach(el=>el.style.animation='none')}
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',e=>{const id=a.getAttribute('href').slice(1);const el=document.getElementById(id);if(!el)return;e.preventDefault();el.scrollIntoView({behavior:'smooth',block:'start'});el.setAttribute('tabindex','-1');el.focus({preventScroll:!0});setTimeout(()=>el.removeAttribute('tabindex'),1000)})});const navToggle=document.querySelector('.nav-toggle');const navMenu=document.querySelector('.nav-menu');if(navToggle&&navMenu){navToggle.addEventListener('click',()=>{navMenu.classList.toggle('active')})}
document.addEventListener("DOMContentLoaded",()=>{const navLogoText=document.querySelector(".logo-text");const heroName=document.querySelector(".hero-name");const psWords=["[SAFE]","_precise_flick;","CTRL//CMD","XXO","◯ ◯","B42;","▤▤","XX_XX","♡♡","MANTRA;","<_steady_aim;"];let cycleInterval=null;function glitchText(newText){navLogoText.dataset.text=newText;navLogoText.classList.add("valorant-glitch");navLogoText.textContent=newText;setTimeout(()=>{navLogoText.classList.remove("valorant-glitch")},500)}
function startCycling(){let index=Math.floor(Math.random()*psWords.length);clearInterval(cycleInterval);glitchText(psWords[index]);index=(index+1)%psWords.length;cycleInterval=setInterval(()=>{glitchText(psWords[index]);index=(index+1)%psWords.length},2000)}
function stopCycling(){clearInterval(cycleInterval);navLogoText.dataset.text="GAGAN SG";navLogoText.textContent="GAGAN SG"}
const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){startCycling()}else{stopCycling()}})},{threshold:0.3});observer.observe(heroName)});document.getElementById("blur-toggle").addEventListener("click",()=>{document.body.classList.toggle("blur-active")});document.querySelectorAll('.player-card-container').forEach(container=>{const shine=container.querySelector('.pc-shine');let targetX=50,targetY=50;let currentX=50,currentY=50;function animate(){currentX+=(targetX-currentX)*0.1;currentY+=(targetY-currentY)*0.1;shine.style.setProperty('--mx',`${currentX}%`);shine.style.setProperty('--my',`${currentY}%`);requestAnimationFrame(animate)}
animate();container.addEventListener('mousemove',e=>{const rect=container.getBoundingClientRect();targetX=((e.clientX-rect.left)/rect.width)*100;targetY=((e.clientY-rect.top)/rect.height)*100})})
